/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bstdemo_ce171000;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *  class tạo frame chính
 * @author quoczuong
 */
public class BSTDemoFrame extends javax.swing.JFrame {

    BSTree tree;
    BSTPaper p;

    /**
     * Creates new form BSTDemoFrame
     */
    public BSTDemoFrame() {
        initComponents();

        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH); // phong to frame toan man hinh

        tree = new BSTree(1366, 60);
        p = new BSTPaper(tree, 1366, 60);
        pnlPaper.setSize(1366, 500);
        pnlPaper.setLayout(new BorderLayout());
        pnlPaper.add(p, BorderLayout.CENTER);

        traversalResult.setEditable(false);
        traversalResult.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConfig = new javax.swing.JPanel();
        lblNodeValue = new javax.swing.JLabel();
        txtNodeValue = new javax.swing.JTextField();
        btnAddNode = new javax.swing.JButton();
        btnAddRandomValue = new javax.swing.JButton();
        btnPreOrder = new javax.swing.JButton();
        btnInOrder = new javax.swing.JButton();
        btnPostOrder = new javax.swing.JButton();
        traversalResult = new java.awt.TextField();
        searchBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        btnBFS = new javax.swing.JButton();
        btnDFS = new javax.swing.JButton();
        btnBlancing = new javax.swing.JButton();
        pnlPaper = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Binary Search Tree v1");
        setName("frameDemoBST"); // NOI18N

        pnlConfig.setBorder(javax.swing.BorderFactory.createTitledBorder("Congiguration"));

        lblNodeValue.setText("Node's value");

        txtNodeValue.setText("0");
        txtNodeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNodeValueActionPerformed(evt);
            }
        });

        btnAddNode.setText("Add node");
        btnAddNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNodeActionPerformed(evt);
            }
        });

        btnAddRandomValue.setText("Add random value");
        btnAddRandomValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRandomValueActionPerformed(evt);
            }
        });

        btnPreOrder.setText("Pre-Order");
        btnPreOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrderActionPerformed(evt);
            }
        });

        btnInOrder.setText("In-Order");
        btnInOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrderActionPerformed(evt);
            }
        });

        btnPostOrder.setText("Post-Order");
        btnPostOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostOrderActionPerformed(evt);
            }
        });

        traversalResult.setText("Traversal result");
        traversalResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traversalResultActionPerformed(evt);
            }
        });

        searchBtn.setText("Search node");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove node");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear BST");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        btnBFS.setText("BFS BST");
        btnBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBFSActionPerformed(evt);
            }
        });

        btnDFS.setText("DFS BST");
        btnDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFSActionPerformed(evt);
            }
        });

        btnBlancing.setText("Blancing BST");
        btnBlancing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlancingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConfigLayout = new javax.swing.GroupLayout(pnlConfig);
        pnlConfig.setLayout(pnlConfigLayout);
        pnlConfigLayout.setHorizontalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConfigLayout.createSequentialGroup()
                        .addComponent(lblNodeValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddNode)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddRandomValue)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn)
                        .addGap(18, 18, 18)
                        .addComponent(removeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn)
                        .addGap(63, 63, 63)
                        .addComponent(btnBlancing)
                        .addGap(18, 18, 18)
                        .addComponent(btnBFS)
                        .addGap(18, 18, 18)
                        .addComponent(btnDFS)
                        .addGap(18, 18, 18)
                        .addComponent(btnPreOrder)
                        .addGap(18, 18, 18)
                        .addComponent(btnInOrder)
                        .addGap(18, 18, 18)
                        .addComponent(btnPostOrder)
                        .addGap(0, 710, Short.MAX_VALUE))
                    .addComponent(traversalResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlConfigLayout.setVerticalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNodeValue)
                    .addComponent(txtNodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNode)
                    .addComponent(btnAddRandomValue)
                    .addComponent(searchBtn)
                    .addComponent(removeBtn)
                    .addComponent(clearBtn)
                    .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBlancing)
                        .addComponent(btnBFS)
                        .addComponent(btnDFS)
                        .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPreOrder)
                            .addComponent(btnPostOrder)
                            .addComponent(btnInOrder))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(traversalResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlPaper.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlPaperLayout = new javax.swing.GroupLayout(pnlPaper);
        pnlPaper.setLayout(pnlPaperLayout);
        pnlPaperLayout.setHorizontalGroup(
            pnlPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPaperLayout.setVerticalGroup(
            pnlPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(pnlPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNodeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNodeValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNodeValueActionPerformed

    private void btnAddNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNodeActionPerformed
        p.addNode(Integer.parseInt(txtNodeValue.getText()));
    }//GEN-LAST:event_btnAddNodeActionPerformed

    /**
     *  tạo các nút bấm cho chương trình
     * @param min
     * @param max
     * @return
     */
    public static int randomNumber(int min, int max) {
        return min + (int) (Math.random() * ((max - min) + 1));
    }

    private void btnAddRandomValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRandomValueActionPerformed
        p.addNode(randomNumber(0, 99));

    }//GEN-LAST:event_btnAddRandomValueActionPerformed

    private void btnPreOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrderActionPerformed
        tree.preOrder();
        traversalResult.setText(tree.getTraversalResult());
    }//GEN-LAST:event_btnPreOrderActionPerformed

    private void btnInOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrderActionPerformed
        tree.inOrder();
        traversalResult.setText(tree.getTraversalResult());
    }//GEN-LAST:event_btnInOrderActionPerformed

    private void btnPostOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostOrderActionPerformed
        tree.postOrder();
        traversalResult.setText(tree.getTraversalResult());
    }//GEN-LAST:event_btnPostOrderActionPerformed

    private void traversalResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traversalResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traversalResultActionPerformed
    
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        
        p.searchNode(Integer.parseInt(txtNodeValue.getText()));
        traversalResult.setText(p.getStringPath());      
        if (p.getPath().isEmpty()) {
            traversalResult.setText("Not found!");
            JOptionPane.showMessageDialog(this, "The node '" + txtNodeValue.getText() + "' is not found in the BST");
        } 
    }//GEN-LAST:event_searchBtnActionPerformed
    
    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        
       p.searchNode(Integer.parseInt(txtNodeValue.getText()));
        if (p.getPath().isEmpty()) {
            traversalResult.setText("Not found!");
            JOptionPane.showMessageDialog(this, "The node ' " + txtNodeValue.getText() + " ' is not found in the BST");
        } else {
            if (JOptionPane.showConfirmDialog(this, "Do you really want to delete the node '" + txtNodeValue.getText() + "?", "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                System.out.println("Tree Before clear: "+p.getPath().get(p.getPath().size()-1));
                p.deleteNode(Integer.parseInt(txtNodeValue.getText()));
                tree.setPath(p.getPath());
                tree.path.clear();
            }
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
     if (JOptionPane.showConfirmDialog(this, "Do you really want to delete all node in this tree?" , "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                this.tree.clear();
                this.p.clear();
            }
       
    }//GEN-LAST:event_clearBtnActionPerformed

    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        tree.BFS();
        traversalResult.setText("BFS: "+tree.getTraversalResult());
    }//GEN-LAST:event_btnBFSActionPerformed

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
        tree.DFS();
        traversalResult.setText("DFS: "+tree.getTraversalResult());
    }//GEN-LAST:event_btnDFSActionPerformed

    private void btnBlancingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlancingActionPerformed
       p.blancing();
    }//GEN-LAST:event_btnBlancingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BSTDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BSTDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BSTDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BSTDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BSTDemoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNode;
    private javax.swing.JButton btnAddRandomValue;
    private javax.swing.JButton btnBFS;
    private javax.swing.JButton btnBlancing;
    private javax.swing.JButton btnDFS;
    private javax.swing.JButton btnInOrder;
    private javax.swing.JButton btnPostOrder;
    private javax.swing.JButton btnPreOrder;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel lblNodeValue;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlPaper;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton searchBtn;
    private java.awt.TextField traversalResult;
    private javax.swing.JTextField txtNodeValue;
    // End of variables declaration//GEN-END:variables
}
